// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANdG3aKAWY7fJgxI8HDa4MwbeYCwPE4r8',
    appId: '1:1052396341164:web:768f8224210a6d28609c09',
    messagingSenderId: '1052396341164',
    projectId: 'floraheart-79578',
    authDomain: 'floraheart-79578.firebaseapp.com',
    storageBucket: 'floraheart-79578.firebasestorage.app',
    measurementId: 'G-RPH75RPE84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxKdYRKxAGRk-iRoo_Eeoi9uLOSUbTTJ0',
    appId: '1:1052396341164:android:9e342ff523268051609c09',
    messagingSenderId: '1052396341164',
    projectId: 'floraheart-79578',
    storageBucket: 'floraheart-79578.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJrjiuRA6dKxuGqwPcGgfLCVDfJdF5v8',
    appId: '1:1052396341164:ios:d2100bbd42573ed5609c09',
    messagingSenderId: '1052396341164',
    projectId: 'floraheart-79578',
    storageBucket: 'floraheart-79578.firebasestorage.app',
    iosBundleId: 'com.example.floraheart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJrjiuRA6dKxuGqwPcGgfLCVDfJdF5v8',
    appId: '1:1052396341164:ios:d2100bbd42573ed5609c09',
    messagingSenderId: '1052396341164',
    projectId: 'floraheart-79578',
    storageBucket: 'floraheart-79578.firebasestorage.app',
    iosBundleId: 'com.example.floraheart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANdG3aKAWY7fJgxI8HDa4MwbeYCwPE4r8',
    appId: '1:1052396341164:web:25b66ca417427697609c09',
    messagingSenderId: '1052396341164',
    projectId: 'floraheart-79578',
    authDomain: 'floraheart-79578.firebaseapp.com',
    storageBucket: 'floraheart-79578.firebasestorage.app',
    measurementId: 'G-TSXYGV3CYN',
  );
}
